### ISSUE TITLE
A few JEI improvements

### ISSUE THREAD

**Issue by DisasterMoo** [TerraFirmaCraft/TerraFirmaCraft#1046]
Created this issue to collect ideas and recommendations on what should be improved in JEI integration, currently:
- [x] Barrel Fluid mixing recipe (show the wooden bucket in slot + the right amount for a bucket's worth in the fluid input and output) (see #989).
- [x] Salting recipes (see #1018).
- [x] Randomize food recipes (see #998).
- [x] Fix JEI question mark in some GUIs (see #907).
- [x] Fix recipes error-ing in log.
- [ ] Add Charcoal Pit to JEI (see #588)

**Comment by alcatrazEscapee** [comment]
To add to this:
 - Unmold recipes are erroring in the log about no output, but are displaying fine in JEI due to having a custom recipe wrapper implementation. Is there a way we could fix the log spam (very minor problem)? Otherwise, this approach would be food for barrel fluid mixing recipes, and perhaps salting recipes. (the other option as mentioned in the issue would be splitting them per meat type, but that's probably less friendly to pack makers.)

**Comment by alcatrazEscapee** [comment]
Seeing as the only thing left here is #588, there's not really a reason to leave this open anymore.
